GIT_URL = 'github.com'
PROJECT_NAME_LENGTH = 200
PROJECT_STATUS_LENGTH = 6
PROJECT_PAGINATE_COUNT = 12

STATUS_OPEN = "open"
STATUS_CLOSED = "closed"
PROJECT_STATUS_CHOICES = [
    (STATUS_OPEN, "Открыт"),
    (STATUS_CLOSED, "Закрыт"),
]

SKILL_NAME_LENGTH = 124
SKILL_COUNT_SHOW = 10

USER_NAME_LENGTH = 124
USER_PHONE_LENGTH = 12
USER_ABOUT_LENGTH = 256
USER_PAGINATE_COUNT = 12
AVATAR_BG_COLOR = "#6C5CE7"
AVATAR_SIZE = 200
FONT_SIZE = 100
BBOX_START = (0, 0)
TEXT_COLOR = "white"


LOGIN_PATH_URL = 'users:login'
LOGOUT_PATH_REDIRECT_URL = '/projects/list/'
LOGIN_PATH_REDIRECT_URL = '/projects/list/'
